# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'BankUI' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for BankUI

  pod 'RealmSwift'
  pod 'GoogleMaps'
  pod 'FirebaseCrashlytics'
  pod 'Firebase/Analytics'

  target 'BankUITests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'BankUIUITests' do
    # Pods for testing
  end

end
